# Generated by Django 5.2 on 2025-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID unique du client sur Stripe.', max_length=255, null=True, verbose_name='ID Client Stripe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text="ID unique de l'abonnement actif sur Stripe.", max_length=255, null=True, verbose_name='ID Abonnement Stripe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('incomplete', 'Incomplet'), ('inactive', 'Inactif')], default='inactive', max_length=20, null=True, verbose_name='Statut Abonnement Stripe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nom'),
        ),
    ]
