# Generated by Django 5.2 on 2025-04-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_key', models.CharField(choices=[('new_product', 'Lancer un nouveau produit ou service'), ('new_market', 'Explorer un nouveau marché ou pays'), ('optimize_model', 'Optimiser un modèle économique existant'), ('funding', 'Simuler une levée de fonds ou un financement'), ('team', 'Recruter ou renforcer une équipe'), ('automation', 'Automatiser ou digitaliser un processus'), ('diversify', "Diversifier l'activité ou pivoter le business model"), ('external_change', 'Anticiper un changement externe'), ('m_and_a', 'Préparer une fusion, acquisition ou partenariat')], help_text='La catégorie principale à laquelle cette question appartient.', max_length=50, verbose_name="Axe d'Analyse Associé")),
                ('question_text', models.TextField(help_text="La question telle qu'elle sera posée à l'utilisateur.", verbose_name='Texte de la Question')),
                ('response_type', models.CharField(choices=[('text', 'Texte Libre (court)'), ('textarea', 'Texte Libre (long)'), ('number', 'Nombre (entier ou décimal)'), ('boolean', 'Oui / Non'), ('choice', 'Choix Multiple (à définir)')], default='text', max_length=20, verbose_name='Type de Réponse Attendue')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordre dans lequel afficher la question pour un axe donné (0, 1, 2...).', verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=False, verbose_name='Réponse obligatoire ?')),
                ('placeholder_text', models.CharField(blank=True, help_text='Texte indicatif affiché dans le champ de réponse.', max_length=255, null=True, verbose_name="Texte d'aide (Placeholder)")),
            ],
            options={
                'verbose_name': 'Question Guidée',
                'verbose_name_plural': 'Questions Guidées',
                'ordering': ['axis_key', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Réponse Fournie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='guided_analysis.guidingquestion', verbose_name='Question Guidée')),
                ('scenario_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_responses', to='analysis.scenariorequest', verbose_name="Demande d'Analyse Associée")),
            ],
            options={
                'verbose_name': 'Réponse Utilisateur Guidée',
                'verbose_name_plural': 'Réponses Utilisateur Guidées',
                'ordering': ['scenario_request', 'question__order'],
                'unique_together': {('scenario_request', 'question')},
            },
        ),
    ]
