# Generated by Django 5.2 on 2025-04-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('global', 'Conseil Global'), ('product_launch', 'Lancement Produit'), ('cost_optimization', 'Optimisation Coûts'), ('other', 'Autre (décrire)')], default='global', max_length=50, verbose_name='Type de scénario')),
                ('user_description', models.TextField(blank=True, help_text='Détaillez en quelques lignes votre projet ou la question spécifique à analyser.', null=True, verbose_name='Décrivez votre projet/question')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_requests', to='company.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_data', models.JSONField(blank=True, null=True, verbose_name='Données Générées (JSON)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.scenariorequest')),
            ],
        ),
    ]
