# Generated by Django 5.2 on 2025-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new_product', 'Lancer un nouveau produit ou service'), ('new_market', 'Explorer un nouveau marché ou pays'), ('optimize_model', 'Optimiser un modèle économique existant'), ('funding', 'Simuler une levée de fonds ou un financement'), ('team', 'Recruter ou renforcer une équipe'), ('automation', 'Automatiser ou digitaliser un processus'), ('diversify', "Diversifier l'activité ou pivoter le business model"), ('external_change', 'Anticiper un changement externe (inflation, réglementation, concurrence)'), ('m_and_a', 'Préparer une fusion, acquisition ou partenariat stratégique'), ('other', 'Autre (champ libre)')], default='new_product', max_length=50, verbose_name="Axe d'analyse principal")),
                ('user_description', models.TextField(blank=True, help_text='Détaillez en quelques lignes votre projet ou la question spécifique à analyser.', null=True, verbose_name='Décrivez votre projet/question')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_data', models.JSONField(blank=True, null=True, verbose_name='Données Générées (JSON)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
