# Generated by Django 5.2 on 2025-04-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariorequest',
            name='company_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_requests', to='company.companyprofile'),
        ),
    ]
