# Generated by Django 5.2 on 2025-04-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariorequest',
            name='request_type',
            field=models.CharField(choices=[('new_product', 'Lancer un nouveau produit ou service'), ('new_market', 'Explorer un nouveau marché ou pays'), ('optimize_model', 'Optimiser un modèle économique existant'), ('funding', 'Simuler une levée de fonds ou un financement'), ('team', 'Recruter ou renforcer une équipe'), ('automation', 'Automatiser ou digitaliser un processus'), ('diversify', "Diversifier l'activité ou pivoter le business model"), ('external_change', 'Anticiper un changement externe (inflation, réglementation, concurrence)'), ('m_and_a', 'Préparer une fusion, acquisition ou partenariat stratégique'), ('other', 'Autre (champ libre)')], default='new_product', max_length=50, verbose_name="Axe d'analyse principal"),
        ),
    ]
