# Generated by Django 5.2 on 2025-04-14 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariorequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioresult',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.scenariorequest'),
        ),
    ]
