# Generated by Django 5.2 on 2025-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fixed', 'Fixe'), ('variable', 'Variable')], max_length=10, verbose_name='Type de charge')),
                ('description', models.CharField(max_length=255, verbose_name='Description (ex: Loyer, Salaires, Matières premières)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant Annuel Estimé (€)')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité")),
                ('activity_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de produits ou services')),
                ('market_scope', models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], max_length=20, null=True, verbose_name='Marché')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Chiffre d'Affaires (CA)")),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du Produit / Service')),
                ('revenue_contribution', models.DecimalField(decimal_places=2, help_text='Montant du CA généré par ce produit/service sur la dernière année complète.', max_digits=15, verbose_name='Contribution au CA Annuel (€)')),
                ('description', models.TextField(blank=True, help_text='Décrivez brièvement ce produit ou service.', null=True, verbose_name='Description (quelques mots)')),
            ],
        ),
    ]
