# Generated by Django 5.2 on 2025-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='description',
            field=models.TextField(blank=True, help_text='Décrivez brièvement ce produit ou service.', null=True, verbose_name='Description (quelques mots)'),
        ),
    ]
